### ISSUE TITLE
Migrate from compilerflasher to using codebender's builder service

### ISSUE THREAD

**Issue by fpapadopou** [codebendercc/BlocklyDuino#6]
Assigned to @azyth & @kyleoliveira 

In the first implementation of our BlocklyDuino project, we used the compilerflasher library in order to perform post requests to the compiler (among many other things like serial monitor, flashing etc).
In fact, the request is not sent to the compiler server directly but passes through a route (codebender.cc/utilities/compile) of the codebender website.
In Symfony, the code behind this route is called an "action". So this action uses php's curl in order to make a post request to the builder. You can find more on builder's API and requests [here](https://github.com/codebendercc/builder/wiki/Builder-API).
The bad thing about this, is that every request needs to get through the codebender website, and there is actually no reason to do that in the case of the BlocklyDuino.
One way to avoid depending on codebender, is to create an action-like code within BlocklyDuino, which will be able to perform an HTTP POST request to the builder, and hanlde the response properly. 
The rest of the compilerflasher functionality should remain the same.
Maybe we will need to discuss about disabling the compilerflasher functions that send requests to codebender's compile action.

The suggested way to implement the above, is Silex and Guzzle. Please take some time reading the documentation about these two and let us know if anything need to be clarified.

**Comment by kyleoliveira** [comment]
Of the two options (Silex and Guzzle), which would you prefer? I'm kinda leaning towards Guzzle.

**Comment by tzikis** [comment]
Yo Kyle,
Silex and Guzzle are not exclusive, but rather complimentary. Silex is a PHP micro-framework (a la Sinatra), which is great for small projects, and gives you a template engine, a configuration engine, etc. it's really lightweight, which is why it's best for you to use it for this task (you shouldn't need to create more than 2-3 URLs for the compilation).

Then, your PHP code in silex will need some way to make an HTTP request to the Builder server. To do that, you can use:
- PHP's file_get_contents() with the URL as the argument, which is horrible for that job
- cURL and PHP's curl library, which is what we use on our server. It's pretty ubiquitous and straightforward
- Guzzle, which is the new kid on the block, and a lot of people seen to be using it. Supposedly very easy to use and powerful

I hope this clears things up a bit. If not, feel free to ask more questions

**Comment by kyleoliveira** [comment]
That makes sense. Thanks for clearing that up.

**Comment by kyleoliveira** [comment]
What path should we use for the builder? The API page only mentions a local installation.

Also, will you be providing authorization keys we can use to test this?

**Comment by tzikis** [comment]
Good question. As far as I know, @fpapadopou is, or was, working on an improved documentation for builder, but he started feeling sick today, and only got worse later on.

He's also the only one who knows how to give you an API key for use with our live Builder setup, so you might need to wait a bit. I will try to remember to call him tomorrow and see if I can create a key for you guys with his help. I'll keep you posted on that

**Comment by kyleoliveira** [comment]
Ok thanks.

I was wondering about something else as well. If the requirement is simply to communicate directly to the builder, and we do this via a RESTful HTTP interface, is there any specific requirement that we do it via Silex and Guzzle? I'm asking because this project is all JavaScript so far. I know there are JavaScript-based ways for sending HTTP requests to RESTful interfaces. If we're not going to integrate this directly with the normal Codebender interface, it seems like forcing it into a PHP framework might add on unnecessary complexity. I don't mean to be contrary, but am I missing something?

**Comment by tzikis** [comment]
Right. The main point is that you need some kind of backend, because you can't or shouldn't make direct calls from the JS running in the browser, depending on how you see it.

Can't because the browser will not allow you to make an AJAX request to another host, I.e. builder.codebender.cc, but this can be bypassed (although it's not the best idea), so let's talk about why we shouldn't.

Well, that's because you don't want to expose the server, or the API key used to talk to the builder to anyone else. So there needs to be some kind of background app that securely communicates the code to builder.

Now, you might be enticed to say "well  we can use node.js and keep everything in JavaScript", which is correct, and I'm not against that in principal (not sure about the rest of the guys though). So, in theory, you can use any framework or micro framework, and any language, be it python, PHP, or even Go (please don't do it in Go!). I am personally pro experimenting with new technologies in small projects, but there is a downside that we won't be able to help you out as much. Or, in other words, we suggested Silex & Guzzle because we can leverage our troubleshooting experience, so when you stumble onto something, we will have a higher chance of fixing it.

At least that's my take, but I'm no longer the guy who has to review and support the code you write for years to come, so take it with a grain of salt, and give weight to what John or Fotis decide.

Ps, sorry for the wall of text, I get carried away sometimes

**Comment by kyleoliveira** [comment]
That all makes sense, that's why I asked :) Thanks!

**Comment by spiliot** [comment]
So I see @tzikis mentioned the wrong guy a few messages above, fotis is @fpapadopou not fakedrake.

Back to the issue at hand, I wouldn't want to jump in and tell you what language to do it in. I leave it to you to weight the pros and cons for the options you have in mind and let us know what you suggest in the end.

As pointers to help, you should pick something that fits the job, is relatively self contained _and_ easily maintainable. For example, a language that you will need to create a dev environment for or compile each time with shared libraries doesn't look like a good choice for this kind of job to me despite the potential speed since throughput isn't the issue.

Finally your api key is http://builder.codebender.cc:8080/compile?api_key=blocklyduino. It is limited to a few thousand requests per day which should be lots more than enough. Since this is essentially public, I'll keep an eye on usage and if I see anything weird I'll block it and send you a new one privately.

**Comment by azyth** [comment]
just for reference is @spiliot John?

**Comment by spiliot** [comment]
Yeap @azyth, I should have said so, sorry for the confusion.

**Comment by kyleoliveira** [comment]
So, we've tried swapping in URLs within the CompilerFlasher script and that doesn't seem to work. We've also tried to simply put the CompilerFlasher script file as-is in our project and reference it from there, and it also doesn't work.

Do you have any suggestions? We're wondering if there's something special either within the browser plugin, or within the CompilerFlasher script that would be keeping this from working.

**Comment by fpapadopou** [comment]
Hey @kyleoliveira and @azyth !!

I'm going to try to make it as clear as I can. 

First off, I noticed that (writing this on Mar 10th 2015 c. 4:30 PM (EET)), blockly.codebender.cc cannot load properly on Google Chrome of Mozilla Firefox. After some digging, I found that your Silex app, renders a twig file that uses several `../../path/to/css/or/js/files` paths. Given the location of the twig file, these files should be `../../../path/to/css/or/js/files`. 

So I manually edited the `/var/www/BlocklyDuino/src/views/blockly.html.twig` file and changed them, which brings us to the next conclusion. We shouldn't use string constants for paths in twig files, because this makes us dig in  the code and look for them, everytime we need to change something in our code. 

Perhaps there is a way to use assets with Silex and twig, and [here](http://silex.sensiolabs.org/doc/cookbook/assets.html) you can find some more info about how to do that. 

The next thing, was that some `manifest` property (where did that come from??)  in the html tag, caused some weird caching on all the files sent by the BlocklyDuino app, which almost drove me insane, so I replaced it with a normal html tag. Have you got any idea what the use of this `manifest` property is?
By the way, even after that, I could only load blockly.codebender.cc from Chrome's private browsing.

Another error, I got on the compilerflasher execution, is that you initialize the compilerflasher like this `compilerflasher = new compilerflasher(getFiles());`, that is you pass the object returned by `getFiles` function to the compilerflasher, instead of the `getFiles` function itself. Note that the `getFiles` function is a callback to the compilerflasher. The right way to do this is `compilerflasher = new compilerflasher(getFiles);`

After that, I tried to change the url in the `compilerflasher.getbin` function. So I replaced the `https://codebender.cc/utilities/compile/` to `http://builder.codebender.cc`. That's what we had told you to do, but it won't work (sorry for that, I should have thought of it from the beginning). The reason is quite simple. Changing the url, you make a request from blocklyduino.codebender.cc to builder.codebender.cc, which is illegal, because it's a cross origin POST request (both sub-domains belong to the same domain). And the reason why it works with `codebender.cc/utilities/compile/`, is that the PHP code behind that route begins with this `header('Access-Control-Allow-Origin: *');`. This allows cross-origin requests (meaning from blockly --> utilities/compile). For security reasons, this header setting is not used on the builder, and that's why you can't create a POST request from the browser to the builder. 
Because of all the above, you should create PHP "action" which would handle sending the POST request  with the payload to the builder url that we gave you. You can have look at the [compileAction](https://github.com/codebendercc/bachelor/blob/master/Symfony/src/Codebender/UtilitiesBundle/Controller/DefaultController.php#L696) of the bachelor version of the codebender website and get a better view of what I said (please note it's an older version and does not change header access control).
I believe you should be able to create a similar action in Silex. Then all you have to do, is override the `compilerflasher.getbin` function and make its requests point to the Silex action you've created.

That's all for now. If you have any further questions please let me know. 
_May the force be with you_

PS
You can find all the changes I made by ssh-ing to the blockly.codebender.cc server and getting to the `/var/www/BlocklyDuino` directory. A simple `git diff` should show you the lines changed. After you've fixed these issues on your local you can `git checkout -- /var/www/BlocklyDuino/src/views/blockly.html.twig` on the server installation (from within the git repo).

**Comment by kyleoliveira** [comment]
@fpapadopou 

Thanks for the insights. Here are my thoughts regarding your questions:

1) Constant resource paths
- Fair point. We haven't invested much time into how Silex can locate that stuff, but we can work on that.

2) Manifest property / Caching
- That comes from the Blocklyduino project (see the original index.html file for reference). I added it recently when I noticed some 404 errors in the logs and found that we hadn't carried it over when converting to Twig. We'll remove that, but we'll need to also remove it in some other places (frame.html, methinks).
- I have noticed the caching, and now that you mention it, that makes sense. With respect to your not being able to see the page when you're not in Incognito/Private mode, try completely clearing your browser cache. In Firefox you'll need to clear the offline data for this site as well.

3) POST request
We've implemented a PHP action for the compile (it's been there 1-2 weeks now) at /compile and /compile/show. The latter is for testing and displays the Request and Response. The former passes stuff through and returns the results. We'll use /compile as the URI/path for communicating with the Builder.

As I mentioned earlier, when we try to replace the compilerflasher.getbin function with our URL (blockly.codebender.cc/compile) and reference a file that is modified as such and is located in our project, nothing works. If I'm reading this right, is that simply because we need to replace _all_ references to codebender.cc (and associated paths) with references to our URL(s) and pass things through there?

4) General
It would be helpful for us to know a little more about what your objectives are regarding this project. Maybe we can talk about this on Friday, connection willing?

Thanks!

**Comment by fpapadopou** [comment]
@kyleoliveira here I am again!

I did some more debugging on your code. I replace the URL with the `blockly.codebender.cc/compile`, which returns an `Invalid input` error, from what saw on the browser's network console tab. After dumping the request you send from javaScript, I got this 

``` json
"{"files":[{"filename":"sketch.ino","content":"{"files":[{"filename":"sketch.ino","content":"void setup()\n{\n\n}\n\n\nvoid loop()\n{\n\n}\n"}],"format":"binary","version":"105","build":{"mcu":"atmega328p","f_cpu":"16000000L","core":"arduino","variant":"standard"}}"}],"libraries":[],"logging":true,"format":"binary","version":"105","build":{"mcu":"atmega328p","f_cpu":"16000000L","core":"arduino","variant":"standard"}}"
```

 and I think I should have gotten this 

``` json
{"files":[{"filename":"test_project.ino","content":"void setup()\n{\n\t\n}\n\nvoid loop()\n{\n\t\n}\n\n"}],"format":"binary","version":"105","build":{"mcu":"atmega328p","f_cpu":"16000000L","core":"arduino","variant":"standard"}}
```

This means that you double-add something to the request, which is not correct, according to the builder.
So I would start with dumping the requests and response I get. I've also used a great app for Chrome, it's called Advanced REST Client, and you can create POST and GET requests with any content you like to any URL. It should help you debug your code. I tried using your /compile route with this tool and it didn't 
work with a valid JSON input either.

I don't think you should change any other references to codebender.cc within the `compilerflasher`, except for the one that is located in the `getbin` function. Have I understood your question or am I missing something?

As for the last question, the purpose of this project, is to be a standalone project, which uses codebender's builder service, along with several other external libraries and resources. Apart from setting  up the project, the next steps include writing Unit/Functional tests for your code, continuous integration methods (such as Travis, which is used by the rest of the codebender projects), design improvements, moving from bash-script installation to auto-deployment scripts (maybe using Chef) and stuff like that. In general it's meant to be one of codebender's contributions to the IOT/maker community.

**Comment by kyleoliveira** [comment]
Sorry, I should have specified what to send to /compile: just send the code. We have some PHP in place that handles the formatting of the request. So the response you got is expected. That may change depending on how we have to mess with the JavaScript, of course.

We'll try messing with the getbin function again. Maybe the caching was the issue? I dunno. I hate working with JavaScript sometimes.

Thanks for the extra background.

**Comment by fpapadopou** [comment]
No problem Kyle! You know, I still haven't completely understood how the /compile works with the rest of the blockly app. However, Github comments are not very helpful for that. That's why you might have to create a wiki within the Github repo, explaining how the app works, what external services it uses and how, in other words, document the work you've done so far. How does that sound? Of course we'll do this after we make the compilation work.

**Comment by kyleoliveira** [comment]
Will do. For simplicity, I've mapped all the paths I could find in the compilerflasher script to paths in our app (see app\Routes::addBuilderRoute). All of those paths _work_ - if you hit any of the get paths that would normally fill up the select statements you'll see that the correct JSON is returned and if you use curl to communicate with the post paths you get back what you'd expect.

What isn't working (still) is the JavaScript. I've tried changing all the get and post requests that I can find in our project's revised compilerflasher script (blocklyflasher.js) so that they point to the paths in our app. Despite that, the dropdowns don't even fill up. Any ideas where we're going wrong?

Until we sort this out, I've set up the instance at blockly.codebender.cc with this last commit but changed it to use the original compilerflasher.js. That way it'll keep working if you need to show it to somebody or something.

**Comment by kyleoliveira** [comment]
This should be ready to close once pull request #11 is merged in.

**Comment by fpapadopou** [comment]
@kyleoliveira @azyth what you are doing wrong is that in your blockly twig file, you initialize a _<b>b</b>locklyflasher = new Blocklyflasher(whatever)_ and in your blocklyflasher.js file, in the boards- and programmers- callbacks, you use a _<b>B</b>locklyflasher_. That's why you don't get any boards/programmers. The fix is applied on the blockly server and you can commit it to your code. You can also check out the comments I've posted on your #11 pull request and change the corresponding parts of the code.

**Comment by kyleoliveira** [comment]
@fpapadopou No, we got it to work. The main issue was the one you mentioned a while back where we were passing in getFiles incorrectly.

~~Please do not change anything on the Blockly server - it had been set up with the changes with #11 and was working as intended. If it wasn't appearing correctly to you, you may have needed to clear your cache.~~

Touche. I was thinking that particular issue was due to not having an actual Arduino plugged into the computer. Still, could you put that kind of thing on a branch? Then we don't have to log into the server to look at the changes, etc.

**Comment by fpapadopou** [comment]
The issue is covered by #11 and everything seems to be fine, so I'm closing the issue
